Django_example/Django_example/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('newyear/',include("newyear.urls")),
    # path('',include("hello.urls")),
    path('tasks/',include("task.urls"))
]

Django_example/hello/urls.py
from django.urls import path

from . import views
# list of all allowable urls
urlpatterns=[
    path("", views.index1 , name="index"),
    path("<str:name>", views.greet , name="greet"),
    path("likith", views.likith , name="likith")
]

Django_example/newyear/urls.py
from django.urls import path

from . import views
# list of all allowable urls
urlpatterns=[
    path("",views.index,name="index")
]

Django_example/task/urls.py
from django.urls import path

from . import views
app_name="task"
urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.add,name="add")
]

Django_example/hello/models.py
from django.db import models

# Create your models here.

Django_example/newyear/models.py
from django.db import models

# Create your models here.

Django_example/task/models.py
from django.db import models

# Create your models here.

Django_example/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse("HELLO!")
#to render entire html page
def index1(request):
     return render(request,"hello/index.html")
def likith(request):
    return HttpResponse("Hello to you")

def greet(request,name):
    return render(request,"hello/greet.html",{
        "name":name.capitalize()
    })

Django_example/newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.month==1 and now.day==1
    })

Django_example/task/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

tasks=[]

class NewTaskForm(forms.Form):
    task=forms.CharField(label="New Task")

# Create your views here.
def index(request):
    return render(request,"task/index.html",{
        "tasks":tasks
    })
def add(request):
    if request.method == "POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            form.cleaned_data["tasks"]
            tasks.append(tasks)
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request,"task/add.html",{
                "form":form
            })
    return render(request,"task/add.html",{
        "form":NewTaskForm()
    })

Django_example/hello/templates/hello/greet.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hi</title>
</head>
<body>
    <h1>Hello {{name }}!</h1>
</body>
</html>

Django_example/hello/templates/hello/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>HELLO</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>HELLO WORLD!</h1>
    </body>
</html>

Django_example/newyear/templates/newyear/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it NEW YEAR?</title>
    <link  href="{% static 'newyear/styles.css' %}" rel="stylesheet">
</head>
<body>
    {% if newyear %}
        <h1>Yes</h1>
    {% else %}
        <h1>No</h1>
    {% endif %}
</body>
</html>

Django_example/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>ADD Task</h1>
    <form action="{% url 'task:add' %}" method="post" >
        {% csrf_token %}
       {{ form }}
        <input type="submit" value="submit">
    </form>
    <a href="{% url 'task:index' %}">To view the tasks</a>
{% endblock %}

Django_example/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Task are</h1>
    <ol>
        {% for task in tasks %}
            <li>{{ tasks }}</li>
        {% endfor %}
    </ol>
    <a href="{% url 'task:add' %}">To add a new task</a>
{% endblock %}

Django_example/task/templates/task/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TASKS</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>